development:
  cloud_name: "music-connects"
  api_key: "669625935539453"
  api_secret: "PSNnuz6dUmyESOoAj6cbNTBsWGE"
  secure: true
  cdn_subdomain: true
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: "music-connects"
  api_key: "669625935539453"
  api_secret: "PSNnuz6dUmyESOoAj6cbNTBsWGE"
  secure: true
  cdn_subdomain: true
  enhance_image_tag: true
  static_file_support: true
